"""Shared constants for :mod:`drf_error_response_standardizer`.

Centralizing header names and defaults here avoids typos scattered across
the middleware, exception handler, and OpenAPI integration, and gives users
a single place to look up what headers the package reads and writes.
"""

from __future__ import annotations

from typing import Final

#: Media type used for RFC 9457 Problem Details responses.
PROBLEM_CONTENT_TYPE: Final[str] = "application/problem+json"

#: Default ``type`` member for problems that have no more specific URI,
#: per RFC 9457 section 3.1.1.
ABOUT_BLANK: Final[str] = "about:blank"

#: Request/response header used to propagate a correlation ID supplied by
#: the caller (e.g. an upstream gateway) or generated by
#: :class:`~drf_error_response_standardizer.middleware.CorrelationIdMiddleware`.
CORRELATION_ID_HEADER: Final[str] = "X-Correlation-ID"

#: Request/response header used to propagate a per-request ID. Distinct
#: from the correlation ID: a correlation ID typically spans an entire
#: user-facing transaction across multiple services, while a request ID
#: identifies exactly one HTTP request/response pair.
REQUEST_ID_HEADER: Final[str] = "X-Request-ID"

#: W3C Trace Context header (https://www.w3.org/TR/trace-context/). When
#: present, the trace ID portion is extracted and included in problem
#: responses so that a client-reported error can be correlated with
#: distributed tracing backends (Jaeger, Tempo, Honeycomb, etc.).
TRACEPARENT_HEADER: Final[str] = "traceparent"

#: ``request.META`` / ``request.headers`` attribute names corresponding to
#: the headers above (Django exposes incoming headers on ``request.META``
#: using the ``HTTP_`` prefixed, upper-cased, underscore form).
CORRELATION_ID_META_KEY: Final[str] = "HTTP_X_CORRELATION_ID"
REQUEST_ID_META_KEY: Final[str] = "HTTP_X_REQUEST_ID"
TRACEPARENT_META_KEY: Final[str] = "HTTP_TRACEPARENT"

#: Attribute names used to stash the resolved IDs on the Django
#: ``HttpRequest`` object so the exception handler can read them back
#: without re-parsing headers.
REQUEST_CORRELATION_ID_ATTR: Final[str] = "correlation_id"
REQUEST_REQUEST_ID_ATTR: Final[str] = "request_id"
REQUEST_TRACE_ID_ATTR: Final[str] = "trace_id"

#: Machine-readable code used for the catch-all "unhandled exception"
#: problem type produced when no more specific mapping applies.
UNKNOWN_ERROR_CODE: Final[str] = "server_error"

#: Machine-readable code used for aggregate validation-error problems.
VALIDATION_ERROR_CODE: Final[str] = "validation_error"

#: JSON Pointer separator used when flattening nested serializer errors,
#: e.g. ``author/email`` for ``{"author": {"email": [...]}}``.
POINTER_SEPARATOR: Final[str] = "/"
