[tox]
envlist =
    py{310,311,312,313}-django42-drf{314,315}
    py{310,311,312,313}-django{50,51}-drf{314,315}
    py{311,312,313}-django52-drf{314,315}
    lint
    typecheck
isolated_build = true

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313

[testenv]
package = wheel
wheel_build_env = .pkg
extras = test
deps =
    django42: django>=4.2,<4.3
    django50: django>=5.0,<5.1
    django51: django>=5.1,<5.2
    django52: django>=5.2,<5.3
    drf314: djangorestframework>=3.14,<3.15
    drf315: djangorestframework>=3.15,<3.17
commands =
    pytest {posargs:--cov --cov-report=term-missing}

[testenv:lint]
skip_install = false
extras = dev
commands =
    ruff check .
    black --check .

[testenv:typecheck]
extras = dev
commands =
    mypy src

[testenv:docs]
extras = docs
commands =
    mkdocs build --strict
