"""Django settings integration for :mod:`drf_notification`.

All configuration lives under a single Django setting, ``NOTIFICATIONS``, a
dictionary of overrides merged on top of :data:`DEFAULTS`. Settings are
validated and cached lazily on first access, and the cache is invalidated
automatically when Django's ``setting_changed`` signal fires (which makes
``@override_settings(NOTIFICATIONS={...})`` work correctly in tests).

Example:
    .. code-block:: python

        # settings.py
        NOTIFICATIONS = {
            "BACKENDS": {
                "sms": "myproject.notifications.backends.TwilioBackend",
            },
            "RATE_LIMITS": {"email": "20/day"},
        }
"""

from __future__ import annotations

from typing import Any, Final

from django.conf import settings
from django.core.exceptions import ImproperlyConfigured
from django.test.signals import setting_changed
from django.utils.functional import cached_property

from drf_notification.constants import (
    CHANNEL_EMAIL,
    CHANNEL_IN_APP,
    CHANNEL_PUSH,
    CHANNEL_SMS,
    CHANNEL_WEBHOOK,
    DIGEST_IMMEDIATE,
)

USER_SETTINGS_NAME: Final[str] = "NOTIFICATIONS"

#: Default values for every recognized setting. See ``docs/settings.md``
#: for the full description of each key.
DEFAULTS: Final[dict[str, Any]] = {
    #: Maps a channel constant to the dotted path of the
    #: :class:`~drf_notification.backends.base.NotificationBackend`
    #: subclass used to deliver on it. Override a single channel by
    #: providing only that key; the rest keep their defaults.
    "BACKENDS": {
        CHANNEL_EMAIL: "drf_notification.backends.email.EmailBackend",
        CHANNEL_SMS: "drf_notification.backends.console.ConsoleBackend",
        CHANNEL_PUSH: "drf_notification.backends.console.ConsoleBackend",
        CHANNEL_IN_APP: "drf_notification.backends.inapp.InAppBackend",
        CHANNEL_WEBHOOK: "drf_notification.backends.webhook.WebhookBackend",
    },
    #: Per-channel rate limits as ``"count/period"`` strings (``period``
    #: is one of ``second``, ``minute``, ``hour``, ``day``), or ``None``
    #: to disable rate limiting for that channel. Channels omitted from
    #: this dict are unlimited.
    "RATE_LIMITS": {
        CHANNEL_EMAIL: "50/day",
        CHANNEL_SMS: "10/day",
        CHANNEL_PUSH: "100/day",
        CHANNEL_WEBHOOK: "200/day",
    },
    #: Maximum number of delivery attempts (the first attempt plus this
    #: many retries) before a failed notification is left in the
    #: ``failed`` state permanently.
    "MAX_RETRIES": 3,
    #: Base delay, in seconds, for exponential retry backoff:
    #: attempt *n* is retried after ``RETRY_BACKOFF_SECONDS * 2**(n-1)``.
    "RETRY_BACKOFF_SECONDS": 300,
    #: Default ``digest_frequency`` for newly created
    #: :class:`~drf_notification.models.NotificationSettings` rows.
    "DEFAULT_DIGEST_FREQUENCY": DIGEST_IMMEDIATE,
    #: Timeout, in seconds, for outbound webhook HTTP requests.
    "WEBHOOK_TIMEOUT": 5.0,
    #: ``From`` address used by :class:`~drf_notification.backends.email.EmailBackend`.
    #: When ``None``, falls back to Django's own ``DEFAULT_FROM_EMAIL``.
    "FROM_EMAIL": None,
    #: When ``True``, :func:`~drf_notification.notify.notify` dispatches
    #: delivery through the Celery task
    #: :func:`~drf_notification.tasks.deliver_notification_task` instead
    #: of sending synchronously in-process. Requires the ``celery`` extra
    #: and a configured Celery app.
    "USE_CELERY": False,
    #: Maximum age, in seconds, of a signed single-event unsubscribe link
    #: generated by :func:`~drf_notification.unsubscribe.generate_unsubscribe_url`.
    #: The persistent "unsubscribe from everything" link
    #: (``NotificationSettings.unsubscribe_token``) never expires.
    "UNSUBSCRIBE_TOKEN_MAX_AGE": 60 * 60 * 24 * 30,
}

_TYPE_CHECKS: Final[dict[str, type | tuple[type, ...]]] = {
    "BACKENDS": dict,
    "RATE_LIMITS": dict,
    "MAX_RETRIES": int,
    "RETRY_BACKOFF_SECONDS": int,
    "DEFAULT_DIGEST_FREQUENCY": str,
    "WEBHOOK_TIMEOUT": (int, float),
    "FROM_EMAIL": (str, type(None)),
    "USE_CELERY": bool,
    "UNSUBSCRIBE_TOKEN_MAX_AGE": int,
}


class _NotificationSettings:
    """Lazily-evaluated, validated, cache-invalidating settings object."""

    def __init__(self) -> None:
        setting_changed.connect(self._on_setting_changed)

    @cached_property
    def _user_settings(self) -> dict[str, Any]:
        raw = getattr(settings, USER_SETTINGS_NAME, {})
        if not isinstance(raw, dict):
            raise ImproperlyConfigured(
                f"The '{USER_SETTINGS_NAME}' Django setting must be a dict, "
                f"got {type(raw).__name__}."
            )
        unknown_keys = set(raw) - set(DEFAULTS)
        if unknown_keys:
            raise ImproperlyConfigured(
                f"Unknown key(s) in '{USER_SETTINGS_NAME}': {sorted(unknown_keys)}. "
                f"Valid keys are: {sorted(DEFAULTS)}."
            )
        merged = dict(DEFAULTS)
        for key, value in raw.items():
            if isinstance(value, dict) and isinstance(merged.get(key), dict):
                merged[key] = {**merged[key], **value}
            else:
                merged[key] = value
        for key, expected_type in _TYPE_CHECKS.items():
            if not isinstance(merged[key], expected_type):
                raise ImproperlyConfigured(
                    f"'{USER_SETTINGS_NAME}[\"{key}\"]' must be of type "
                    f"{expected_type}, got {type(merged[key]).__name__}."
                )
        if merged["MAX_RETRIES"] < 0:
            raise ImproperlyConfigured(f"'{USER_SETTINGS_NAME}[\"MAX_RETRIES\"]' must be >= 0.")
        return merged

    def __getitem__(self, key: str) -> Any:
        if key not in DEFAULTS:
            raise KeyError(f"Invalid setting: {key!r}. Valid keys are: {sorted(DEFAULTS)}.")
        return self._user_settings[key]

    def _on_setting_changed(self, *, sender: Any, setting: str, **kwargs: Any) -> None:
        if setting == USER_SETTINGS_NAME:
            self.__dict__.pop("_user_settings", None)


app_settings = _NotificationSettings()


def get_setting(key: str) -> Any:
    """Return the effective value of a single package setting.

    Args:
        key: One of the keys documented in :data:`DEFAULTS` (e.g.
            ``"BACKENDS"``, ``"RATE_LIMITS"``, ``"MAX_RETRIES"``).

    Returns:
        The user-configured value, deep-merged with defaults for dict
        settings (``BACKENDS``, ``RATE_LIMITS``), otherwise the default.

    Raises:
        KeyError: If ``key`` is not a recognized setting name.
        django.core.exceptions.ImproperlyConfigured: If the
            ``NOTIFICATIONS`` setting is malformed.
    """
    return app_settings[key]
