"""Generates one DRF ``Serializer`` class per ``components.schemas`` entry.

Classes are emitted in dependency order (a schema referenced by another
via ``$ref`` is emitted first) using :mod:`graphlib`. A genuine circular
reference between two schemas cannot be expressed as two nested,
in-order class definitions in plain Python, so the *second* class
encountered in such a cycle gets a plain ``DictField`` in place of the
nested serializer, with a comment explaining why - this package does
not silently guess at a workaround (e.g. ``PrimaryKeyRelatedField``-style
laziness) for something that requires a project-specific decision.
"""

from __future__ import annotations

import graphlib
from typing import Any

from drf_api_reverse.naming import comment_safe, serializer_class_name, to_snake_case
from drf_api_reverse.type_mapping import field_spec, ref_target

REGION_PREFIX = "serializer"

_HEADER = '''"""DRF serializers generated by drf-api-reverse from the OpenAPI contract.

Regions marked BEGIN/END DRF-API-REVERSE GENERATED are regenerated by
``drf-api-reverse scaffold`` - anything you add outside of them survives
a re-run untouched. See https://mahmoudgshake.github.io/MahmoudPackages/drf-api-reverse/architecture/
for how regeneration and drift detection work.
"""

from __future__ import annotations

from rest_framework import serializers
'''


def region_key(schema_name: str) -> str:
    """Return the merge-region key for a component schema's serializer."""
    return f"{REGION_PREFIX}:{schema_name}"


def generate_serializer_regions(schema: dict[str, Any]) -> dict[str, str]:
    """Generate one region body per ``components.schemas`` entry.

    Args:
        schema: The full parsed OpenAPI document.

    Returns:
        A mapping of :func:`region_key` to the generated class source
        for that schema (no surrounding markers - the caller adds
        those), in the same iteration order the schemas should be
        written to the file in.
    """
    schemas: dict[str, Any] = (schema.get("components") or {}).get("schemas") or {}
    order = _emission_order(schemas)

    regions: dict[str, str] = {}
    defined: set[str] = set()
    for name in order:
        regions[region_key(name)] = _generate_class(name, schemas[name], defined=defined)
        defined.add(name)
    return regions


def render_file(schema: dict[str, Any]) -> str:
    """Render a brand-new ``serializers.py`` from scratch (no merge)."""
    regions = generate_serializer_regions(schema)
    body = "\n\n".join(
        f"# === BEGIN DRF-API-REVERSE GENERATED: {key} ===\n{code}\n"
        f"# === END DRF-API-REVERSE GENERATED: {key} ==="
        for key, code in regions.items()
    )
    return f"{_HEADER}\n\n{body}\n" if body else f"{_HEADER}\n"


def _emission_order(schemas: dict[str, Any]) -> list[str]:
    sorter: graphlib.TopologicalSorter[str] = graphlib.TopologicalSorter()
    for name, schema_obj in schemas.items():
        deps = _direct_refs(schema_obj, set(schemas)) - {name}
        sorter.add(name, *deps)
    try:
        return list(sorter.static_order())
    except graphlib.CycleError:
        return list(schemas)


def _direct_refs(schema_obj: dict[str, Any], component_names: set[str]) -> set[str]:
    refs: set[str] = set()
    for field_schema in (schema_obj.get("properties") or {}).values():
        refs |= _refs_from_field(field_schema)
    return refs & component_names


def _refs_from_field(field_schema: dict[str, Any]) -> set[str]:
    target = ref_target(field_schema)
    if target is not None:
        return {target}
    if field_schema.get("type") == "array":
        return _refs_from_field(field_schema.get("items") or {})
    return set()


def _generate_class(name: str, schema_obj: dict[str, Any], *, defined: set[str]) -> str:
    class_name = serializer_class_name(name)
    properties: dict[str, Any] = schema_obj.get("properties") or {}
    required: set[str] = set(schema_obj.get("required") or [])

    if not properties:
        return f"class {class_name}(serializers.Serializer):\n    pass"

    lines = [f"class {class_name}(serializers.Serializer):"]
    for field_name, field_schema in properties.items():
        spec = field_spec(field_schema, required=field_name in required)
        if spec.ref is not None and spec.ref not in defined:
            comment = f"  # circular/forward reference to {comment_safe(spec.ref)}: define manually"
            lines.append(f"    {to_snake_case(field_name)} = serializers.DictField(){comment}")
        else:
            lines.append(f"    {to_snake_case(field_name)} = {spec.expression}")
    return "\n".join(lines)
