"""Generates ``urls.py`` router registrations, one per resource group."""

from __future__ import annotations

from typing import Any

from drf_api_reverse.codegen.operations import parse_resource_groups
from drf_api_reverse.naming import viewset_class_name

REGION_PREFIX = "url"

_HEADER = '''"""URL routing generated by drf-api-reverse from the OpenAPI contract.

Regions marked BEGIN/END DRF-API-REVERSE GENERATED are regenerated by
``drf-api-reverse scaffold`` - anything you add outside of them survives
a re-run untouched.
"""

from __future__ import annotations

from rest_framework.routers import DefaultRouter

from .views import *  # noqa: F403

router = DefaultRouter()
'''

_FOOTER = "\nurlpatterns = router.urls\n"


def region_key(group_key: str) -> str:
    """Return the merge-region key for a resource group's registration."""
    return f"{REGION_PREFIX}:{group_key}"


def generate_url_regions(schema: dict[str, Any]) -> dict[str, str]:
    """Generate one router-registration line per resource group.

    Args:
        schema: The full parsed OpenAPI document.

    Returns:
        A mapping of :func:`region_key` to the generated registration
        statement for that group.
    """
    regions: dict[str, str] = {}
    for group in parse_resource_groups(schema):
        prefix = group.base_path.strip("/")
        class_name = viewset_class_name(group.key)
        # repr(), not an f-string quote: prefix/group.key come from the
        # schema and must never be able to break out of the string
        # literal into the generated source (see docs/security.md).
        regions[region_key(group.key)] = (
            f"router.register({prefix!r}, {class_name}, basename={group.key!r})"
        )
    return regions


def render_file(schema: dict[str, Any]) -> str:
    """Render a brand-new ``urls.py`` from scratch (no merge)."""
    regions = generate_url_regions(schema)
    body = "\n\n".join(
        f"# === BEGIN DRF-API-REVERSE GENERATED: {key} ===\n{code}\n"
        f"# === END DRF-API-REVERSE GENERATED: {key} ==="
        for key, code in regions.items()
    )
    parts = [_HEADER]
    if body:
        parts.append(body)
    parts.append(_FOOTER)
    return "\n\n".join(parts) if body else f"{_HEADER}{_FOOTER}"
