"""Generates one DRF ``ViewSet`` class per resource group.

Every generated method body is a single, explicit
``raise NotImplementedError(...)`` naming the exact operation it stands
in for - this package scaffolds the *shape* of your API from the
contract, it does not (and cannot) invent your business logic. See
:mod:`drf_api_reverse.codegen.operations` for how paths are grouped and
classified.
"""

from __future__ import annotations

from typing import Any

from drf_api_reverse.codegen.operations import Operation, ResourceGroup, parse_resource_groups
from drf_api_reverse.naming import comment_safe, serializer_class_name, viewset_class_name
from drf_api_reverse.type_mapping import ref_target

REGION_PREFIX = "viewset"

_HEADER = '''"""DRF viewsets generated by drf-api-reverse from the OpenAPI contract.

Regions marked BEGIN/END DRF-API-REVERSE GENERATED are regenerated by
``drf-api-reverse scaffold`` - anything you add outside of them survives
a re-run untouched. Every generated method raises ``NotImplementedError``:
fill in the real implementation, the raise is the marker of what's left
to do, not a bug.
"""

from __future__ import annotations

from rest_framework import viewsets
from rest_framework.decorators import action

from .serializers import *  # noqa: F403
'''


def region_key(group_key: str) -> str:
    """Return the merge-region key for a resource group's viewset."""
    return f"{REGION_PREFIX}:{group_key}"


def generate_viewset_regions(schema: dict[str, Any]) -> dict[str, str]:
    """Generate one region body per resource group.

    Args:
        schema: The full parsed OpenAPI document.

    Returns:
        A mapping of :func:`region_key` to the generated class source.
    """
    groups = parse_resource_groups(schema)
    return {region_key(group.key): _generate_class(group, schema) for group in groups}


def render_file(schema: dict[str, Any]) -> str:
    """Render a brand-new ``views.py`` from scratch (no merge)."""
    regions = generate_viewset_regions(schema)
    body = "\n\n".join(
        f"# === BEGIN DRF-API-REVERSE GENERATED: {key} ===\n{code}\n"
        f"# === END DRF-API-REVERSE GENERATED: {key} ==="
        for key, code in regions.items()
    )
    return f"{_HEADER}\n\n{body}\n" if body else f"{_HEADER}\n"


def _generate_class(group: ResourceGroup, schema: dict[str, Any]) -> str:
    class_name = viewset_class_name(group.key)
    serializer_ref = _infer_serializer(group, schema)

    lines = [f"class {class_name}(viewsets.ViewSet):"]
    if serializer_ref:
        lines.append(f"    serializer_class = {serializer_class_name(serializer_ref)}")
    else:
        lines.append(
            "    serializer_class = None  # no $ref response schema found - set this by hand"
        )

    unsupported = [op for op in group.operations if op.kind == "unsupported"]
    for op in unsupported:
        note = (
            f"Not auto-scaffolded: {op.method.upper()} {comment_safe(op.path)} (unsupported shape)"
        )
        lines.append(f"    # {note}")

    standard_ops = [op for op in group.operations if op.kind in ("collection", "detail")]
    for op in standard_ops:
        lines.append("")
        lines.append(f"    def {op.drf_method_name}(self, request, *args, **kwargs):")
        message = f"Implement {op.method.upper()} {op.path}"
        lines.append(f"        raise NotImplementedError({message!r})")

    for url_path, ops in _group_nested_actions(group.operations).items():
        methods = ", ".join(repr(op.method) for op in ops)
        method_name = ops[0].drf_method_name
        lines.append("")
        lines.append(f"    @action(detail=True, methods=[{methods}], url_path={url_path!r})")
        lines.append(f"    def {method_name}(self, request, *args, **kwargs):")
        summary = ", ".join(f"{op.method.upper()} {op.path}" for op in ops)
        lines.append(f"        raise NotImplementedError({f'Implement {summary}'!r})")

    return "\n".join(lines)


def _group_nested_actions(operations: list[Operation]) -> dict[str, list[Operation]]:
    grouped: dict[str, list[Operation]] = {}
    for op in operations:
        if op.kind != "nested_action" or op.action_url_path is None:
            continue
        grouped.setdefault(op.action_url_path, []).append(op)
    return grouped


def _infer_serializer(group: ResourceGroup, schema: dict[str, Any]) -> str | None:
    paths: dict[str, Any] = schema.get("paths") or {}
    for op in group.operations:
        if op.kind not in ("collection", "detail"):
            continue
        operation = (paths.get(op.path) or {}).get(op.method) or {}
        responses: dict[str, Any] = operation.get("responses") or {}
        for response in responses.values():
            content = (response or {}).get("content") or {}
            media = content.get("application/json") or {}
            body_schema = media.get("schema") or {}
            if body_schema.get("type") == "array":
                body_schema = body_schema.get("items") or {}
            target = ref_target(body_schema)
            if target:
                return target
    return None
